FROM docker.bintray.io/jfrog/artifactory-oss:4.16.0
VOLUME /var/run/docker.sock
VOLUME /var/opt/jfrog/artifactory/data
VOLUME /var/opt/jfrog/artifactory/logs
VOLUME /var/opt/jfrog/artifactory/etc
EXPOSE 8081